//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Humanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int id { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Monto_total { get; set; }
    }
}
