//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Humanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacacione
    {
        public int Id { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public Nullable<int> Correspondiente_a { get; set; }
        public string Comentarios { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
